@startuml
skinparam linetype ortho
"curl" --> "libc6"
"libc6" --> "libgcc-s1"
"libgcc-s1" --> "gcc-14-base"
"libgcc-s1" --> "libc6"
"curl" --> "libcurl4t64"
"libcurl4t64" --> "libbrotli1"
"libbrotli1" --> "libc6"
"libcurl4t64" --> "libc6"
"libcurl4t64" --> "libgssapi-krb5-2"
"libgssapi-krb5-2" --> "libc6"
"libgssapi-krb5-2" --> "libcom-err2"
"libcom-err2" --> "libc6"
"libgssapi-krb5-2" --> "libk5crypto3"
"libk5crypto3" --> "libc6"
"libk5crypto3" --> "libkrb5support0"
"libkrb5support0" --> "libc6"
"libgssapi-krb5-2" --> "libkrb5-3"
"libkrb5-3" --> "libc6"
"libkrb5-3" --> "libcom-err2"
"libkrb5-3" --> "libk5crypto3"
"libkrb5-3" --> "libkeyutils1"
"libkeyutils1" --> "libc6"
"libkrb5-3" --> "libkrb5support0"
"libkrb5-3" --> "libssl3t64"
"libssl3t64" --> "libc6"
"libgssapi-krb5-2" --> "libkrb5support0"
"libcurl4t64" --> "libidn2-0"
"libidn2-0" --> "libc6"
"libidn2-0" --> "libunistring5"
"libunistring5" --> "libc6"
"libcurl4t64" --> "libldap2"
"libldap2" --> "libc6"
"libldap2" --> "libgnutls30t64"
"libgnutls30t64" --> "libc6"
"libgnutls30t64" --> "libgmp10"
"libgmp10" --> "libc6"
"libgnutls30t64" --> "libhogweed6t64"
"libhogweed6t64" --> "libc6"
"libhogweed6t64" --> "libgmp10"
"libhogweed6t64" --> "libnettle8t64"
"libnettle8t64" --> "libc6"
"libgnutls30t64" --> "libidn2-0"
"libgnutls30t64" --> "libnettle8t64"
"libgnutls30t64" --> "libp11-kit0"
"libp11-kit0" --> "libc6"
"libp11-kit0" --> "libffi8"
"libffi8" --> "libc6"
"libffi8" --> "libgcc-s1"
"libgnutls30t64" --> "libtasn1-6"
"libtasn1-6" --> "libc6"
"libgnutls30t64" --> "libunistring5"
"libldap2" --> "libsasl2-2"
"libsasl2-2" --> "libc6"
"libsasl2-2" --> "libsasl2-modules-db"
"libsasl2-modules-db" --> "libc6"
"libsasl2-modules-db" --> "libdb5.3t64"
"libdb5.3t64" --> "libc6"
"libsasl2-2" --> "libssl3t64"
"libcurl4t64" --> "libnghttp2-14"
"libnghttp2-14" --> "libc6"
"libcurl4t64" --> "libpsl5t64"
"libpsl5t64" --> "libc6"
"libpsl5t64" --> "libidn2-0"
"libpsl5t64" --> "libunistring5"
"libcurl4t64" --> "librtmp1"
"librtmp1" --> "libc6"
"librtmp1" --> "libgmp10"
"librtmp1" --> "libgnutls30t64"
"librtmp1" --> "libhogweed6t64"
"librtmp1" --> "libnettle8t64"
"librtmp1" --> "zlib1g"
"zlib1g" --> "libc6"
"libcurl4t64" --> "libssh-4"
"libssh-4" --> "libc6"
"libssh-4" --> "libgssapi-krb5-2"
"libssh-4" --> "libssl3t64"
"libssh-4" --> "zlib1g"
"libcurl4t64" --> "libssl3t64"
"libcurl4t64" --> "libzstd1"
"libzstd1" --> "libc6"
"libcurl4t64" --> "zlib1g"
"curl" --> "zlib1g"
@enduml
